### ISSUE TITLE
'adb' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by 4040MAR** [aerosol-can/PhoneSploit#19]
I'm trying to use phonesploit on windows command prompt but it is showing me this error what should I do"'adb' is not recognized as an internal or external command,
operable program or batch file."

**Comment by aerosol-can** [comment]
you need to unzip the adb file first.
also, screenshots of your problem would be helpful.

**Comment by 4040MAR** [comment]
this problem is solved but i need one more help its showing me this error whenever I'm trying to connect to any phone: "cannot connect to 103.***.***.*:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)"
what shall i do please help?

**Comment by aerosol-can** [comment]
the device should have an open adb listener on port 5555 for TCP/IP connection.

if you're testing it on your phone,
you can do it by connecting your device via usb and saying `tcpip PORT` where PORT is the port number.

**Comment by 4040MAR** [comment]
is there any way without connecting to a computer as i want to check on my little brothers device and he won't give me his phone
?

**Comment by aerosol-can** [comment]
you will have to take the phone, go to developer settings, turn on ADB and authenticate your computer for a persistent connection.

**Comment by vandalop** [comment]
aerosol can is scammer he gives his videos  as  super usefull but in reality its useless

**Comment by vandalop** [comment]
> you will have to take the phone, go to developer settings, turn on ADB and authenticate your computer for a persistent connection.

u scammer
