### ISSUE TITLE
error: cannot connect to daemon 

### ISSUE THREAD

**Issue by cpu2020** [aerosol-can/PhoneSploit#20]
i keep getting "error: cannot connect to daemon"
"* failed to start daemon"

how do i fix this??

**Comment by aerosol-can** [comment]
what platform are you using?
a screenshot of the problem would be more helpful.

**Comment by cpu2020** [comment]
hi,

i am using linux 


![image](https://user-images.githubusercontent.com/67715225/101536231-a23ed500-3991-11eb-8823-838fbbc2a01e.png)
this is the error i keep getting

**Comment by aerosol-can** [comment]
try doing 

```
apt uninstall adb
apt install adb
```

**Comment by cpu2020** [comment]
> try doing 
> 
> ```
> apt uninstall adb
> apt install adb
> ```

Nice thanks this works now :D
