### ISSUE TITLE
daemon error

### ISSUE THREAD

**Issue by pakivirus** [aerosol-can/PhoneSploit#30]
It is showing error when I try to connect phone in my termux terminal
Error:
daemon not running. starting it now at tcp:5038 *
error: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
Pls help

**Comment by maxlinux123** [comment]
![image](https://user-images.githubusercontent.com/67342098/128569768-857eeb55-b95e-44e0-a213-40136b7e954e.jpeg)

**Comment by aerosol-can** [comment]
refer to #5
