### ISSUE TITLE
Import "colorama" could not be resolved from source

### ISSUE THREAD

**Issue by nothingishere123** [aerosol-can/PhoneSploit#31]
I am getting this error in phonesploit.py (Import "colorama" could not be resolved from source)
'pip install colorama' this too didnt helped me

**Comment by aerosol-can** [comment]
try `pip3 install colorama`

**Comment by nothingishere123** [comment]
Yes installed but now this error is poppping up
'adb' is not recognized as an internal or external command,
operable program or batch file :(

**Comment by nothingishere123** [comment]
`'adb' is not recognized as an internal or external command,
operable program or batch file`

**Comment by aerosol-can** [comment]
unzip adb.rar file or download the latest adb executables from [https://developer.android.com/studio/releases/platform-tools](here)

**Comment by aerosol-can** [comment]
unzip the adb. rar file or download the latest adb executables from [here](https://developer.android.com/studio/releases/platform-tools)

**Comment by nothingishere123** [comment]
done
←[37mphonesploit←[31m(main_menu) ←[37m>
this is showing?
what shall i do

**Comment by aerosol-can** [comment]
it's the program running.

**Comment by nothingishere123** [comment]
bruh but i cant read properly
the original author wrote this to read it easyly
