### ISSUE TITLE
error: no devices/emulators found

### ISSUE THREAD

**Issue by MalliRk** [aerosol-can/PhoneSploit#36]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![Screenshot_2022-01-14-21-11-08-155_com termux](https://user-images.githubusercontent.com/97071003/149543062-70f06001-faab-4343-8f21-d13361e05bdf.jpg)

**Comment by aerosol-can** [comment]
refer #5

**Comment by shodan97** [comment]
how to fix the error (error: no devices/emulators found List of devices attached)
