### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by bigbyrd69** [aerosol-can/PhoneSploit#37]
`phonesploit(main_menu) > 1`
`sh: 1: adb: not found`

i tried this too

`sudo apt update`

`sudo apt install android-tools-adb android-tools-fastboot`

**Comment by aerosol-can** [comment]
what device are you trying to run it on?

**Comment by bigbyrd69** [comment]
> 

i am using VM in my pc
in desbian based linux os

**Comment by aerosol-can** [comment]
refer [this](https://github.com/aerosol-can/PhoneSploit#how-to-install-on-linux)
