### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Hacker-Joy7** [aerosol-can/PhoneSploit#43]
![Screenshot_2023-05-28-18-55-07-39_84d3000e3f4017145260f7618db1d683](https://github.com/aerosol-can/PhoneSploit/assets/133258834/d57a314d-a7a9-4588-bdfe-6911814369b7)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aerosol-can** [comment]
adb package isn't installed. not sure if it is available for termux now but the work around was unstable back in the day.
