### ISSUE TITLE
No connection could be made because the target machine actively refused it. (10061)

### ISSUE THREAD

**Issue by ArtricPlayer** [aerosol-can/PhoneSploit#9]
hello im having this issue alot of time , im tying to figure out why ,
i founded that the ip im trying to connect is exists and ok , but its looks like the hostname listener is down 
how could i fix it thank you !.

**Comment by 01010000-kumar** [comment]
is the adb listener on some port other than 5555?

**Comment by pranavramesh123** [comment]
no it in port 5555

**Comment by pranavramesh123** [comment]
even i am having the same problem

**Comment by 01010000-kumar** [comment]
what error message did you get?
a screenshot would be more helpful.

**Comment by maninder9211** [comment]
hey i am facing issue :
daemon not starting when I use Phonesploit in termux.
here is error:
daemon not running. starting it now at tcp:5038 *
error: could not install smartsocket listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
List of devices attached
* daemon not running. starting it now at tcp:5038 *
error: could not install smartsocket listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon

Please help me...
![Screenshot_2020-11-14-08-17-05](https://user-images.githubusercontent.com/74127552/99137939-0b615000-2653-11eb-80af-0388fcb5dfab.png)

**Comment by MstrOrcus** [comment]
I'm having this error.

**Comment by aerosol-can** [comment]
https://github.com/aerosol-can/PhoneSploit/issues/5#issuecomment-691205867
